apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-sm
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: todoapp
  namespaceSelector:
    matchNames:
      - todoapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http
